In [1]:
import torch
import numpy as np

## Initialize tensor

In [3]:
data = [[1, 2], [3, 4]]
tensor = torch.tensor(data)
tensor

np_arr = np.array(data)
tensor_fnp = torch.from_numpy(np_arr)
tensor_fnp

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(tensor) # Retain shape and datatype
x_ones

x_rand = torch.rand_like(tensor, dtype=torch.float)
x_rand

tensor([[0.2032, 0.3767],
        [0.4200, 0.5779]])

### Shape and Attr

In [15]:
shape = (2, 3,)
rand_sor = torch.rand(shape)
rand_sor
ones_sor = torch.ones(shape)
ones_sor
zeros_sor = torch.zeros(shape)
zeros_sor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
print(f"Shape of zero tensor {zeros_sor.shape} ")
print(f"Dtype of ones tensor {ones_sor.dtype} ")
print(f"Storage device of rand tensor {rand_sor.device} ")


Shape of zero tensor torch.Size([2, 3]) 
Dtype of ones tensor torch.float32 
Storage device of rand tensor cpu 


In [21]:
# Move tensor to GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [23]:
print(f"Storage device of tensor {tensor.device} ")
tensor

Storage device of tensor cuda:0 


tensor([[1, 2],
        [3, 4]], device='cuda:0')

### Tensor operations

In [31]:
tensor = torch.rand(4, 4)
tensor

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

# Reassign
tensor[:, 1] = 0
tensor


First row: tensor([0.8409, 0.8776, 0.1986, 0.2127])
First column: tensor([0.8409, 0.2412, 0.4565, 0.8573])
Last column: tensor([0.2127, 0.5467, 0.6837, 0.7997])


tensor([[0.8409, 0.0000, 0.1986, 0.2127],
        [0.2412, 0.0000, 0.5599, 0.5467],
        [0.4565, 0.0000, 0.2498, 0.6837],
        [0.8573, 0.0000, 0.9526, 0.7997]])

In [43]:
# Concat
tensor_cat = torch.cat([tensor, tensor, tensor], dim=1)
tensor_stac = torch.stack([tensor, tensor, tensor], dim=1)
tensor_cat[0]
tensor_stac[0]

tensor([[0.8409, 0.0000, 0.1986, 0.2127],
        [0.8409, 0.0000, 0.1986, 0.2127],
        [0.8409, 0.0000, 0.1986, 0.2127]])

#### Arithmatic

In [50]:
# Matrix multiplication

y = tensor @ tensor.T
y
y = tensor.matmul(tensor.T)
y

y_r = torch.rand_like(y)
torch.matmul(tensor, tensor.T, out=y_r)
y_r

tensor([[0.7917, 0.4303, 0.5789, 1.0801],
        [0.4303, 0.6706, 0.6237, 1.1773],
        [0.5789, 0.6237, 0.7382, 1.1761],
        [1.0801, 1.1773, 1.1761, 2.2819]])

In [57]:
# Element-wise multiplication
z = tensor.T * tensor.T
z = tensor.mul(tensor)
z

tensor([[0.7071, 0.0000, 0.0394, 0.0452],
        [0.0582, 0.0000, 0.3135, 0.2989],
        [0.2084, 0.0000, 0.0624, 0.4674],
        [0.7350, 0.0000, 0.9075, 0.6394]])

In [60]:
# Aggregate (sum)
agg = tensor.sum()
agg
agg_itm = agg.item() # only one element tensors can be converted to Python scalars
agg_itm

6.599551200866699

In [68]:
# In place operation
## Operations that store the result into the operand are called in-place.

ones_sor = torch.ones(3, 4)
ones_sor[:, 2] = 0
print(ones_sor, "\n")
ones_sor.add_(5)
ones_sor = ones_sor.add(5) # same as
ones_sor

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]]) 



tensor([[6., 6., 5., 6.],
        [6., 6., 5., 6.],
        [6., 6., 5., 6.]])

## Numpy Bridge

In [73]:
n = tensor.numpy()
n
tensor.mul_(0)
n # operation to tensor reflects numpy array n


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [79]:
np_arr = np.ones((5, 6,))
tensor = torch.from_numpy(np_arr)

np.add(np_arr, 1, out=np_arr)
tensor # operation to np array reflects tensor


tensor([[2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.]], dtype=torch.float64)